apiVersion: v1
kind: Secret
metadata:
  name: argoproj-ssh-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:expertep/gitops.git
  type: helm
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAyDs1kH6nGZeZnGZNv5N6VjXl4qFoXdC0EsikaM9Z+FwAAAJBki0XHZItF
    xwAAAAtzc2gtZWQyNTUxOQAAACAyDs1kH6nGZeZnGZNv5N6VjXl4qFoXdC0EsikaM9Z+Fw
    AAAEDNc5cG50BP0aj3FkBXN9DGvxvuYdGXIz1EhZalpVQfsDIOzWQfqcZl5mcZk2/k3pWN
    eXioWhd0LQSyKRoz1n4XAAAACmFyZ29jZC1ib3QBAgM=
    -----END OPENSSH PRIVATE KEY-----